apiVersion: apps/v1
kind: Deployment
metadata:
    name: rickandmorty-deployment
    namespace: default
    labels:
        app: rickandmorty
spec:
    replicas: 3
    selector:
        matchLabels:
            app: rickandmorty
    template:
        metadata:
            labels:
                app: rickandmorty
        spec:
            containers:
                - name: rickandmorty
                  image: saliht95/rickandmorty:v1
                  ports:
                      - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
    name: rickandmorty-service
    namespace: default
spec:
    selector:
        app: rickandmorty
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000
    type: LoadBalancer